name: CI-MLProject-Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MLflow
        run: |
          pip install --upgrade pip
          pip install mlflow

      - name: Run MLflow Project
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        working-directory: MLProject
        run: |
          echo "Current tracking URI:"
          python - << 'EOF'
          import mlflow
          print(mlflow.get_tracking_uri())
          EOF

          echo "Finding latest run ID..."
          RUN_ID=$(python - << 'EOF'
          import mlflow
          from mlflow.tracking import MlflowClient

          mlflow.set_tracking_uri("sqlite:///mlflow.db")

          client = MlflowClient()
          runs = client.search_runs(
              experiment_ids=["0"],
              order_by=["attributes.start_time DESC"],
              max_results=1,
          )
          print(runs[0].info.run_id)
          EOF
          )

          echo "Latest run_id: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Build Docker image from MLflow model
        working-directory: MLProject
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "heart-disease-ml"

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag heart-disease-ml ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-ml:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-ml:latest

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns